# Generated by Django 3.0.6 on 2020-05-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('appointment', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_user', to='users.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('validating', 'Validating'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='validating', max_length=15),
        ),
    ]
