# Generated by Django 3.0.6 on 2020-05-30 05:36

from django.db import migrations, models
import yema.apps.appointment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200530_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[yema.apps.appointment.validators.AppointmentValidator.validate_future_date]),
        ),
    ]
