# Generated by Django 3.0.6 on 2020-05-30 06:58

from django.db import migrations, models
import django.utils.timezone
import yema.apps.appointment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20200530_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[yema.apps.appointment.validators.AppointmentValidator.validate_future_date]),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
